SELECT PROCESSLIST_ID AS id, 
        PROCESSLIST_USER AS user, 
        PROCESSLIST_HOST AS host, 
        PROCESSLIST_DB AS db, 
        PROCESSLIST_COMMAND AS command, 
        PROCESSLIST_TIME AS time, 
        PROCESSLIST_STATE AS state, 
        LEFT(PROCESSLIST_INFO, 80) AS info
 FROM performance_schema.threads
 WHERE PROCESSLIST_ID IS NOT NULL
 AND PROCESSLIST_COMMAND NOT IN ('Sleep', 'Binlog Dump')
 ORDER BY PROCESSLIST_TIME ASC;